/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author sumanta
 */
public class cal extends javax.swing.JFrame {
    
    private static String action = "";
    private static double numb1 = 0;
    private static double numb2 = 0;
    private static double result = 0;
    
    

  
    public cal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtval = new javax.swing.JTextField();
        num1 = new javax.swing.JButton();
        num2 = new javax.swing.JButton();
        num3 = new javax.swing.JButton();
        num4 = new javax.swing.JButton();
        num5 = new javax.swing.JButton();
        num6 = new javax.swing.JButton();
        num7 = new javax.swing.JButton();
        num8 = new javax.swing.JButton();
        num9 = new javax.swing.JButton();
        numd = new javax.swing.JButton();
        numm = new javax.swing.JButton();
        nums = new javax.swing.JButton();
        numa = new javax.swing.JButton();
        num0 = new javax.swing.JButton();
        nume = new javax.swing.JButton();
        numdot = new javax.swing.JButton();
        numclear = new javax.swing.JButton();
        numback = new javax.swing.JButton();
        numsq = new javax.swing.JButton();
        numx2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("calculator");
        setLocation(new java.awt.Point(250, 500));
        setResizable(false);
        setType(java.awt.Window.Type.UTILITY);

        txtval.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        txtval.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtval.setToolTipText("");

        num1.setText("1");
        num1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num1ActionPerformed(evt);
            }
        });

        num2.setText("2");
        num2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num2ActionPerformed(evt);
            }
        });

        num3.setText("3");
        num3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num3ActionPerformed(evt);
            }
        });

        num4.setText("4");
        num4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num4ActionPerformed(evt);
            }
        });

        num5.setText("5");
        num5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num5ActionPerformed(evt);
            }
        });

        num6.setText("6");
        num6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num6ActionPerformed(evt);
            }
        });

        num7.setText("7");
        num7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num7ActionPerformed(evt);
            }
        });

        num8.setText("8");
        num8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num8ActionPerformed(evt);
            }
        });

        num9.setText("9");
        num9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num9ActionPerformed(evt);
            }
        });

        numd.setText("/");
        numd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numdActionPerformed(evt);
            }
        });

        numm.setText("*");
        numm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nummActionPerformed(evt);
            }
        });

        nums.setText("-");
        nums.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numsActionPerformed(evt);
            }
        });

        numa.setText("+");
        numa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numaActionPerformed(evt);
            }
        });

        num0.setText("0");
        num0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num0ActionPerformed(evt);
            }
        });

        nume.setBackground(new java.awt.Color(153, 153, 153));
        nume.setIcon(new javax.swing.ImageIcon("C:\\Users\\sumanta\\OneDrive\\Documents\\javaSD\\calculator\\src\\equal.png")); // NOI18N
        nume.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numeActionPerformed(evt);
            }
        });

        numdot.setText(".");
        numdot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numdotActionPerformed(evt);
            }
        });

        numclear.setBackground(new java.awt.Color(153, 153, 153));
        numclear.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        numclear.setForeground(new java.awt.Color(204, 0, 0));
        numclear.setText("c");
        numclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numclearActionPerformed(evt);
            }
        });

        numback.setFont(new java.awt.Font("Dialog", 1, 8)); // NOI18N
        numback.setIcon(new javax.swing.ImageIcon("C:\\Users\\sumanta\\OneDrive\\Documents\\javaSD\\calculator\\src\\back.png")); // NOI18N
        numback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numbackActionPerformed(evt);
            }
        });

        numsq.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        numsq.setIcon(new javax.swing.ImageIcon("C:\\Users\\sumanta\\OneDrive\\Documents\\javaSD\\calculator\\src\\square root.png")); // NOI18N
        numsq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numsqActionPerformed(evt);
            }
        });

        numx2.setIcon(new javax.swing.ImageIcon("C:\\Users\\sumanta\\OneDrive\\Documents\\javaSD\\calculator\\src\\x2 .png")); // NOI18N
        numx2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numx2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtval)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 9, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(num1)
                                .addGap(18, 18, 18)
                                .addComponent(num2)
                                .addGap(73, 73, 73))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(num4)
                                .addGap(18, 18, 18)
                                .addComponent(num5)
                                .addGap(73, 73, 73))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(num7, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(num0, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(numdot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(num8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(numclear)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(num6)
                                        .addComponent(num9)
                                        .addComponent(num3)))
                                .addGap(18, 18, 18))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(nume, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(numd, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(numback))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(nums, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(numa, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(numm, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(numsq, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addComponent(numx2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                        .addGap(1, 1, 1)))
                .addGap(0, 48, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(txtval, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(num2)
                                    .addComponent(num3)
                                    .addComponent(numd)
                                    .addComponent(num1))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(num6)
                                        .addComponent(nums))
                                    .addComponent(num5)
                                    .addComponent(num4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(num9)
                                    .addComponent(num8)
                                    .addComponent(num7)
                                    .addComponent(numa)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(numx2, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(numm, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(numdot, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(numclear, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(num0))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(numsq, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nume, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(48, 48, 48))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(numback)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void num1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num1ActionPerformed
        // TODO add your handling code here:
        
       String str = txtval.getText() + num1.getText();
       txtval.setText(str);
        
    }//GEN-LAST:event_num1ActionPerformed

    private void num2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num2ActionPerformed
        // TODO add your handling code here:
        
          String str = txtval.getText() + num2.getText();
       txtval.setText(str);
        
    }//GEN-LAST:event_num2ActionPerformed

    private void num3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num3ActionPerformed
        // TODO add your handling code here:
        
          String str = txtval.getText() + num3.getText();
       txtval.setText(str);
        
    }//GEN-LAST:event_num3ActionPerformed

    private void num4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num4ActionPerformed
        // TODO add your handling code here:
        
          String str = txtval.getText() + num4.getText();
       txtval.setText(str);
        
    }//GEN-LAST:event_num4ActionPerformed

    private void num5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num5ActionPerformed
        // TODO add your handling code here:
        
          String str = txtval.getText() + num5.getText();
       txtval.setText(str);
        
    }//GEN-LAST:event_num5ActionPerformed

    private void num6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num6ActionPerformed
        // TODO add your handling code here:
        
          String str = txtval.getText() + num6.getText();
       txtval.setText(str);  
    }//GEN-LAST:event_num6ActionPerformed

    private void num7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num7ActionPerformed
        // TODO add your handling code here:
        
          String str = txtval.getText() + num7.getText();
       txtval.setText(str);
    }//GEN-LAST:event_num7ActionPerformed

    private void num8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num8ActionPerformed
        // TODO add your handling code here:
        
          String str = txtval.getText() + num8.getText();
       txtval.setText(str);
        
    }//GEN-LAST:event_num8ActionPerformed

    private void num9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num9ActionPerformed
        // TODO add your handling code here:
        
          String str = txtval.getText() + num9.getText();
       txtval.setText(str);
        
    }//GEN-LAST:event_num9ActionPerformed

    private void num0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num0ActionPerformed
        // TODO add your handling code here:
        
          String str = txtval.getText() + num0.getText();
       txtval.setText(str);
        
    }//GEN-LAST:event_num0ActionPerformed

    private void numeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numeActionPerformed
        // TODO add your handling code here:
          numb2 = Integer.valueOf(txtval.getText());
          
          if("+".equals(action)){
             result = (Double) numb1 + numb2 ;
          }
          else if("-".equals(action)){
             result = (Double) numb1 - numb2 ;
          }
          else if("*".equals(action)){
             result = (Double) numb1 * numb2 ;
          }
          else    if("/".equals(action)){
             result = (Double) numb1 / numb2 ;
          }
          
          txtval.setText(String.valueOf(result));
              
                      
        
    }//GEN-LAST:event_numeActionPerformed

    private void numaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numaActionPerformed
        // TODO add your handling code here:
        //action = numa.getText();
        action = "+";
        numb1 = Double.valueOf(txtval.getText());
        txtval.setText("");
    }//GEN-LAST:event_numaActionPerformed

    private void numsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numsActionPerformed
        // TODO add your handling code here:
       // action = nums.getText();
         action = "-";
           numb1 = Double.valueOf(txtval.getText());
        txtval.setText("");
    }//GEN-LAST:event_numsActionPerformed

    private void nummActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nummActionPerformed
        // TODO add your handling code here:
       // action = numm.getText();
         action = "*";
           numb1 = Double.valueOf(txtval.getText());
        txtval.setText("");
    }//GEN-LAST:event_nummActionPerformed

    private void numdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numdActionPerformed
        // TODO add your handling code here:
       // action = numd.getText();
         action = "/";
           numb1 = Double.valueOf(txtval.getText());
        txtval.setText("");
    }//GEN-LAST:event_numdActionPerformed

    private void numdotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numdotActionPerformed
        // TODO add your handling code here:
        
         String str = txtval.getText() + numdot.getText();
       txtval.setText(str); 
    }//GEN-LAST:event_numdotActionPerformed

    private void numclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numclearActionPerformed
        // TODO add your handling code here:
        
        txtval.setText("");
    }//GEN-LAST:event_numclearActionPerformed

    private void numbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numbackActionPerformed
        // TODO add your handling code here:
        String s = txtval.getText();
       s = s.substring(0 , s.length()-1);
       txtval.setText(s);
    }//GEN-LAST:event_numbackActionPerformed

    private void numsqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numsqActionPerformed
        // TODO add your handling code here:
        numb1 = Double.valueOf(txtval.getText());
       double sq = Math.sqrt(numb1);
       
       txtval.setText(String.valueOf(sq));
       
         
    }//GEN-LAST:event_numsqActionPerformed

    private void numx2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numx2ActionPerformed
        // TODO add your handling code here:
        numb1 = Double.valueOf(txtval.getText());
       double p =  Math.pow(numb1, 2);
       txtval.setText(String.valueOf(p));
       
        
    }//GEN-LAST:event_numx2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton num0;
    private javax.swing.JButton num1;
    private javax.swing.JButton num2;
    private javax.swing.JButton num3;
    private javax.swing.JButton num4;
    private javax.swing.JButton num5;
    private javax.swing.JButton num6;
    private javax.swing.JButton num7;
    private javax.swing.JButton num8;
    private javax.swing.JButton num9;
    private javax.swing.JButton numa;
    private javax.swing.JButton numback;
    private javax.swing.JButton numclear;
    private javax.swing.JButton numd;
    private javax.swing.JButton numdot;
    private javax.swing.JButton nume;
    private javax.swing.JButton numm;
    private javax.swing.JButton nums;
    private javax.swing.JButton numsq;
    private javax.swing.JButton numx2;
    private javax.swing.JTextField txtval;
    // End of variables declaration//GEN-END:variables
}
